[package]
name = "error-pile"
description = "All errors for projects managed by Ram Hotel Management apps reside in this crate"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
calamine = "0.26.1"
chrono = "0.4.40"
graph-http = "2.0.2"
graph-rs-sdk = "2.0.3"
russh = "0.51.1"
russh-sftp = "2.1.0"
sea-orm = "1.1.8"
sea-orm-migration = "1.1.8"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.44.2"
url = "2.5.4"
uuid = "1.16.0"
zip = { version = "=2.5.0" }
ocr-client = {git = "https://github.com/Ram-Hotel-Management/ocr-client.git"}